name: Docker Image CI

env:
  today: $(date +%s)
  username: ${{ secrets.DOCKERHUB_USERNAME }}
  password: ${{ secrets.DOCKERHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: $(username)
        password: $(password)
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $(username)/compilers:$(today)
    - name: Push Docker image
      run: docker push $(password)/compilers:$(today)
